#ifndef NNETWORK_H
#define NNETWORK_H

#include <math.h>

// Generated by nnetwork
// Architecture: 1-6-6-1

static inline float sigmoid(float x)    { return 1.0f / (1.0f + expf(-x)); }
static inline float tanh_act(float x)   { return tanhf(x); }
static inline float relu(float x)        { return x > 0.0f ? x : 0.0f; }
static inline float leaky_relu(float x)  { return x > 0.0f ? x : 0.01f * x; }
static inline float linear(float x)      { return x; }

const float w1[6][1] = {
    {-1.27043},
    {-0.294368},
    {0.480057},
    {0.580579},
    {-0.906437},
    {-0.644308}
};
const float b1[6] = {1.45501, 0.337479, -0.441373, 0.0882613, 1.06775, -0.216904};

const float w2[6][6] = {
    {0.537658, -0.214343, -0.290529, -0.74452, -0.08486, -0.109386},
    {-0.585309, -0.53813, -0.210394, -0.281482, -0.0347594, 0.584837},
    {-0.659712, -0.808642, 0.284785, -0.372365, 0.0458452, 0.782509},
    {0.490999, -0.241518, 0.234713, -0.620576, -0.818997, -0.518129},
    {1.63319, 0.529438, -1.1591, -0.488652, 1.79387, 0.161512},
    {0.0278209, 0.721825, 0.800345, 0.0830831, -0.697823, -0.376166}
};
const float b2[6] = {-0.195268, -0.633868, -0.521506, 0.339114, 0.460998, 0.97444};

const float w3[1][6] = {
    {-0.657311, -0.679462, -0.366849, 0.0817016, -1.86531, 0.88678}
};
const float b3[1] = {0.755047};

static inline void predict(const float* input, float* output) {
    float a[6], b[6];
    const float* in = input;
    float* out = a;

    // layer 1 (tanh_act)
    for (int i = 0; i < 6; i++) {
        float sum = b1[i];
        for (int j = 0; j < 1; j++)
            sum += w1[i][j] * in[j];
        out[i] = tanh_act(sum);
    }
    in = out; out = (out == a) ? b : a;

    // layer 2 (tanh_act)
    for (int i = 0; i < 6; i++) {
        float sum = b2[i];
        for (int j = 0; j < 6; j++)
            sum += w2[i][j] * in[j];
        out[i] = tanh_act(sum);
    }
    in = out; out = (out == a) ? b : a;

    // layer 3 (tanh_act)
    for (int i = 0; i < 1; i++) {
        float sum = b3[i];
        for (int j = 0; j < 6; j++)
            sum += w3[i][j] * in[j];
        out[i] = tanh_act(sum);
    }

    for (int i = 0; i < 1; i++)
        output[i] = out[i];
}

#endif // NNETWORK_H
